/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[codeId]': RouteRecordInfo<'/[codeId]', '/:codeId', { codeId: ParamValue<true> }, { codeId: ParamValue<false> }>,
    '/[codeId]/asm': RouteRecordInfo<'/[codeId]/asm', '/:codeId/asm', { codeId: ParamValue<true> }, { codeId: ParamValue<false> }>,
    '/[codeId]/complexity': RouteRecordInfo<'/[codeId]/complexity', '/:codeId/complexity', { codeId: ParamValue<true> }, { codeId: ParamValue<false> }>,
    '/[codeId]/execution': RouteRecordInfo<'/[codeId]/execution', '/:codeId/execution', { codeId: ParamValue<true> }, { codeId: ParamValue<false> }>,
    '/[codeId]/llvm': RouteRecordInfo<'/[codeId]/llvm', '/:codeId/llvm', { codeId: ParamValue<true> }, { codeId: ParamValue<false> }>,
    '/[codeId]/symbol': RouteRecordInfo<'/[codeId]/symbol', '/:codeId/symbol', { codeId: ParamValue<true> }, { codeId: ParamValue<false> }>,
    '/[codeId]/syntax': RouteRecordInfo<'/[codeId]/syntax', '/:codeId/syntax', { codeId: ParamValue<true> }, { codeId: ParamValue<false> }>,
    '/[codeId]/token': RouteRecordInfo<'/[codeId]/token', '/:codeId/token', { codeId: ParamValue<true> }, { codeId: ParamValue<false> }>,
  }
}
